# Generated by Django 5.1.7 on 2025-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="Clave")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Enlace"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "enlace",
                "verbose_name_plural": "enlaces",
                "ordering": ("name",),
            },
        ),
    ]
