# Generated by Django 5.1.7 on 2025-04-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SocialUser",
            new_name="Link",
        ),
    ]
