# Generated by Django 5.1.7 on 2025-04-05 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 5, 0, 35, 56, 749340, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Publicado: ",
            ),
        ),
    ]
