# Generated by Django 5.1.7 on 2025-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="get_post", to="blog.category", verbose_name="Categorias"
            ),
        ),
    ]
